---
- name: Install nginx
  yum: name=nginx state=present

- name: Remove default configuration file
  file:
    path: /etc/nginx/nginx.conf.default
    state: absent
  notify:
    - restart nginx

- name: Make sure conf.d/ exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 755

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - {
      src: "nginx.conf.j2",
      dest: "/etc/nginx/nginx.conf"
      }
    - {
      src: "diaspora.conf.j2",
      dest: "/etc/nginx/conf.d/diaspora.conf"
      }
    - {
      src: "monit.conf.j2",
      dest: "/etc/nginx/conf.d/monit.conf"
      }
  notify: restart nginx

- name: Create dhparam.pem if not exists
  command: >
    openssl dhparam -out {{ ssl_path }}/dhparam.pem 2048
    creates={{ ssl_path }}/dhparam.pem
  tags:
    - ssl

# TODO Currently the stdout is always empty. No way to know if there
# are access logs or not.
- name: Remove nginx access logs if any
  shell: find /var/log/nginx/ -name "*access*" -print0 | xargs --no-run-if-empty -0 rm
  register: rm_result
  changed_when: 'rm_result.stdout != ""'

- name: Enable nginx service
  service: name=nginx state=started enabled=yes
