---
# tasks file for nginx

- name: Install nginx
  yum: name=nginx state=present
  notify: restart nginx
  tags:
    - nginx

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - {
      src: "../templates/nginx.conf.j2",
      dest: "/etc/nginx/nginx.conf"
      }
    - {
      src: "../templates/diaspora.conf.j2",
      dest: "/etc/nginx/conf.d/diaspora.conf"
      }
  notify: restart nginx
  tags:
    - nginx

- name: Create ssl directory
  file:
    path: /etc/ssl/librenet.gr/
    state: directory
    owner: root
    group: root
    mode: 755
  tags:
    - ssl

- name: Check if hdparam.pem exists
  command: test -f /etc/ssl/dhparam.pem
  register: dhparam_pem
  failed_when: false
  tags:
    - ssl

- name: Create dhparam.pem if not exists
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048
  when: dhparam_pem|failed
  tags:
    - ssl

- name: Copy ssl cerificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - {
      src: "../files/ssl/ssl-unified.crt",
      dest: "{{ ssl_cert }}"
      }
    - {
      src: "../files/ssl/ssl.key",
      dest: "{{ ssl_cert_key }}"
      }
  notify: restart nginx
  tags:
    - nginx

# TODO Currently the stdout is always empty. No way to know if there
# are access logs or not.
- name: Remove nginx access logs if any
  shell: find /var/log/nginx/ -name "*access*" -print0 | xargs --no-run-if-empty -0 rm
  register: rm_result
  changed_when: 'rm_result.stdout != ""'
  tags:
    - nginx
