---
# tasks file for nginx

- name: Install nginx
  yum: name=nginx state=present
  notify: restart nginx

- name: Remove default configuration file
  file:
    path: etc/nginx/nginx.conf.default
    state: absent
  notify:
    - restart nginx

- name: Make sure conf.d/ exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 755

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - {
      src: "nginx.conf.j2",
      dest: "/etc/nginx/nginx.conf"
      }
    - {
      src: "diaspora.conf.j2",
      dest: "/etc/nginx/conf.d/diaspora.conf"
      }
    - {
      src: "monit.conf.j2",
      dest: "/etc/nginx/conf.d/monit.conf"
      }
  notify: restart nginx

- name: Create ssl directory
  file:
    path: /etc/ssl/librenet.gr/
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - ssl

- name: Create dhparam.pem if not exists
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048 creates=/etc/ssl/dhparam.pem
  tags:
    - ssl

- name: Copy ssl cerificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0400
  with_items:
    - {
      src: "../files/ssl/ssl-unified.crt",
      dest: "{{ ssl_cert }}"
      }
    - {
      src: "../files/ssl/ssl.key",
      dest: "{{ ssl_cert_key }}"
      }
  notify: restart nginx

# TODO Currently the stdout is always empty. No way to know if there
# are access logs or not.
- name: Remove nginx access logs if any
  shell: find /var/log/nginx/ -name "*access*" -print0 | xargs --no-run-if-empty -0 rm
  register: rm_result
  changed_when: 'rm_result.stdout != ""'

- name: Enable nginx service
  service: name=nginx state=started enabled=yes
