---
- name: Set SELinux to enforcing
  lineinfile:
    dest: /etc/selinux/config
    regexp: ^SELINUX=
    line: SELINUX=enforcing

- name: Install required packages
  yum: name={{ item }} state=latest
  with_items:
    - policycoreutils-python
    - policycoreutils-devel
    - setroubleshoot-server

- name: Check SSH port
  shell: semanage port --list | grep {{ FIREWALLD_SSH_PORT }}
  register: seport
  changed_when: false

- name: Allow non-default SSH port
  command: "semanage port -a -t ssh_port_t -p tcp {{ FIREWALLD_SSH_PORT }}"
  when: seport|failed

- name: Copy SELinux policy modules
  template:
    src: "{{ item }}.te.j2"
    dest: /tmp/{{ item }}.te
  with_items: selinux_modules

- name: Create mod files
  command: "checkmodule -M -m -o {{ item }}.mod {{ item }}.te"
  args:
    chdir: /tmp/
  with_items: selinux_modules

- name: Create compiled modules
  command: "semodule_package -o {{ item }}.pp -m {{ item }}.mod"
  args:
    chdir: /tmp/
  with_items: selinux_modules

- name: Enable modules
  command: "semodule -i {{ item }}.pp"
  args:
    chdir: /tmp/
  with_items: selinux_modules

- name: Remove generated modules
  file:
    path: "/tmp/{{ item }}.*"
    state: absent
  with_items: selinux_modules
