image: python:2-alpine

before_script:
  - apk add --no-cache build-base libffi-dev openssl-dev
  - pip install ansible

syntax check:
  script:
    - rm ansible.cfg # use default ansible.cfg
    - ansible-playbook --syntax-check --list-tasks -i tests/inventory tests/deploy.yml
