---
- hosts: all
  sudo: yes

  vars_files:
    - private.yml

  roles:
    - common
    - users
    - { role: postgres, tags: ['database', 'postgres'] }
    - { role: redis, tags: ['redis'] }
    - { role: diaspora, tags: ['diaspora'] }
    - { role: monit, tags: ['monit'] }
    - { role: ssl, tags: ['ssl'] }
    - { role: nginx, tags: ['nginx'] }

# Enable services on boot.
- include: ./playbooks/services_enable.yml
