---
- hosts: all
  sudo: yes
  sudo_user: root

  roles:
    - common
    - { role: nginx, tags: ['nginx'] }
    - mariadb
    - { role: diaspora, tags: ['diaspora'] }

# Enable services on boot.
- include: ./playbooks/services_enable.yml
