---
- hosts: all
  sudo: true

  vars_files:
    - private.yml

  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: postgres, tags: ['database', 'postgres'] }
    - { role: redis, tags: ['redis'] }
    - { role: diaspora, tags: ['diaspora'] }
    - { role: camo, tags: ['camo'] }
    - { role: monit, tags: ['monit'] }
    - { role: ssl, tags: ['ssl'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: firewalld, tags: ['firewall'] }

# Enable services on boot.
- include: ./playbooks/services_enable.yml
