---
- hosts: all
  sudo: yes
  sudo_user: root

  roles:
    - common
    - { role: nginx, tags: ['nginx'] }
    - { role: mariadb, tags: ['database', 'mariadb'] }
    - { role: diaspora, tags: ['diaspora'] }
    - { role: monit, tags: ['monit'] }

# Enable services on boot.
#- include: ./playbooks/services_enable.yml
