---
- hosts: all
  sudo: yes

  vars_files:
    - private.yml

  roles:
    - common
    - { role: mariadb, tags: ['database', 'mariadb'] }
    - { role: diaspora, tags: ['diaspora'] }
    - { role: monit, tags: ['monit'] }
    - { role: nginx, tags: ['nginx'] }

# Enable services on boot.
- include: ./playbooks/services_enable.yml
