---
# defaults file for diaspora

diaspora_dir: /var/www/diaspora
diaspora_user: diaspora
diaspora_group: diaspora
unicorn_pid: /var/run/diaspora/diaspora.pid
pod_name: 'librenet*'
sitename: 'librenet.gr'
systemd_path: /usr/lib/systemd/system
sidekiq:
  log: /var/log/diaspora/sidekiq.log
