---
- name: Install diaspora system dependencies
  yum: name="{{ item }}" state=present
  with_items:
    - git
    - wget
    - ImageMagick-devel
    - redis
    - nodejs
    - ruby
    - ruby-devel
    - libxslt-devel
    - libxml2-devel
    - gcc
  tags:
    - diaspora

- name: Install bundler
  gem: name=bundler state=present user_install=no
  register: bundler
  tags:
    - gem
    - bundler

- name: Create bundle symlink to /usr/bin
  file: src=/usr/local/bin/bundle dest=/usr/bin/bundle state=link
  tags:
    - bundler

- name: Add diaspora user
  user: name=diaspora comment="Diaspora" shell=/bin/bash
  register: add_user

- name: Create repo directory
  file: >
    path=/var/www/diaspora
    state=directory
    owner=diaspora
    group=diaspora
    mode=755

- name: Ensure /home/diaspora/.ssh/ exists
  sudo_user: diaspora
  file: path=/home/diaspora/.ssh/ state=directory
  tags:
    - ssh

- name: Add github to known_hosts
  sudo_user: diaspora
  shell: "ssh-keyscan -H github.com > /home/diaspora/.ssh/known_hosts"
  register: github_known_hosts
  tags:
    - git
    - ssh

- name: Git checkout librenet branch
  sudo_user: diaspora
  git: >
    repo="{{ git_repo_url }}"
    version="{{ git_branch }}"
    dest="{{ diaspora_dir }}"
    remote=librenet
  when: add_user|success and github_known_hosts|success
  tags:
    - git
    - diaspora
    - deploy
    - assets

- name: Install gem dependencies
  sudo_user: diaspora
  shell: >
    chdir="{{ diaspora_dir }}"
    creates="{{ diaspora_dir }}"/vendor/bundle/
    RAILS_ENV=production /usr/bin/bundle install --without test development --deployment
  register: bundle_install
  when: bundler|success
  tags:
    - gem
    - bundler
    - update

- name: Copy unicorn.rb
  copy: >
    src=unicorn.rb
    dest="{{ diaspora_dir }}/config/unicorn.rb"
    owner=diaspora
    group=diaspora
    mode=644
  notify:
    - restart unicorn
  tags:
    - diaspora
    - config
    - unicorn

- name: Copy diaspora.yml
  template: >
    src=diaspora.yml.j2
    dest="{{ diaspora_dir }}/config/diaspora.yml"
    owner=diaspora
    group=diaspora
    mode=644
  notify:
    - restart unicorn
    - restart sidekiq
  tags:
    - diaspora
    - config
    - private
    - yaml
    - unicorn
    - sidekiq

- name: Copy database.yml
  template: >
    src=database.yml.j2
    dest="{{ diaspora_dir }}/config/database.yml"
    owner=diaspora
    group=diaspora
    mode=644
  register: database_yml
  notify:
    - restart unicorn
    - restart sidekiq
  tags:
    - diaspora
    - config
    - database
    - yaml

- name: Check if database is already populated
  command: test -f "/var/lib/mysql/{{ mysql_databases[0].name }}/aspects.frm"
  ignore_errors: true
  changed_when: false
  register: init_seed
  tags:
    -database

- name: Initial Seed of database (destructive, run only 1st time)
  sudo_user: diaspora
  shell: >
    chdir="{{ diaspora_dir }}"
    RAILS_ENV=production  /usr/bin/bundle exec "rake db:create db:schema:load"
  when: init_seed|failed
  tags:
    - database
    - seed

- name: Migrate database
  sudo_user: diaspora
  shell: >
    chdir="{{ diaspora_dir }}"
    RAILS_ENV=production /usr/bin/bundle exec "rake db:migrate"
  when: bundle_install|success
  tags:
    - update
    - database
    - migration

  # Recompile assets only if app/assets exists and any file is changed
- name: Recompile assets
  sudo_user: diaspora
  shell: >
    chdir="{{ diaspora_dir }}"
    RAILS_ENV=production /usr/bin/bundle exec "rake assets:precompile tmp:cache:clear"
  notify:
    - restart unicorn
  tags:
    - update
    - assets
