---
- name: Install diaspora system dependencies
  yum: name="{{ item }}" state=present
  with_items:
    - git
    - wget
    - ImageMagick-devel
    - nodejs
    - libxslt-devel
    - libxml2-devel
    - gcc
    - patch

- name: Install bundler
  gem: name=bundler state=latest user_install=no
  register: bundler
  tags:
    - gem
    - bundler
    - git
    - database
    - assets
    - diaspora

- name: Create repo directory
  file: >
    path=/var/www/diaspora
    state=directory
    owner=diaspora
    group=diaspora
    mode=0755

- name: Create log directory
  file: >
    path=/var/log/diaspora
    state=directory
    owner=diaspora
    group=diaspora
    mode=0755

- name: Get last remote commit sha
  shell: >
    git ls-remote {{ git_repo_url }} HEAD | awk '{print $1}'
  register: remote_sha
  changed_when: false
  ignore_errors: yes
  tags:
    - git
    - diaspora

- name: Get last local commit sha
  shell: >
    chdir=/var/www/diaspora/
    git rev-parse HEAD
  register: local_sha
  changed_when: false
  ignore_errors: yes
  tags:
    - git
    - diaspora

- name: Git checkout librenet branch
  become_user: diaspora
  git:
    repo: "{{ git_repo_url }}"
    version: "{{ git_branch }}"
    dest: "{{ diaspora_dir }}"
    remote: "{{ git_remote }}"
    accept_hostkey: yes
    force: yes
  when: (remote_sha.stdout != local_sha.stdout or local_sha.stdout == "")
  register: git_checkout
  tags:
    - git
    - deploy
    - diaspora

- name: stat Gemfile.lock
  stat: path={{ diaspora_dir }}/Gemfile.lock
  register: gemfile_lock

- name: Copy diaspora.yml
  template: >
    src=diaspora.yml.j2
    dest="{{ diaspora_dir }}/config/diaspora.yml"
    owner=diaspora
    group=diaspora
    mode=0644
  notify:
    - restart unicorn
    - restart sidekiq
  tags:
    - config
    - private
    - yaml
    - unicorn
    - sidekiq
    - diaspora

- name: Copy database.yml
  template: >
    src=database.yml.j2
    dest="{{ diaspora_dir }}/config/database.yml"
    owner=diaspora
    group=diaspora
    mode=0644
  register: database_yml
  notify:
    - restart unicorn
    - restart sidekiq
  tags:
    - config
    - database
    - yaml
    - postgres
    - diaspora

- name: Copy sidekiq.yml
  template: >
    src=sidekiq.yml.j2
    dest="{{ diaspora_dir }}/config/sidekiq.yml"
    owner=diaspora
    group=diaspora
    mode=0644
  notify:
    - restart sidekiq
  tags:
    - diaspora
    - config
    - sidekiq
    - yaml

- name: Copy newrelic.yml
  template: >
    src=newrelic.yml.j2
    dest="{{ diaspora_dir }}/config/newrelic.yml"
    owner=diaspora
    group=diaspora
    mode=0644
  notify:
    - restart unicorn
  tags:
    - diaspora
    - config
    - newrelic
    - yaml

- name: Copy .bundle/config
  template: >
    src=bundle.config.j2
    dest="{{ diaspora_dir }}/.bundle/config"
    owner=diaspora
    group=diaspora
    mode=0644
  register: bundle_config
  notify:
    - restart unicorn
  tags:
    - diaspora
    - config
    - bundler

- name: Install gem dependencies
  become_user: diaspora
  shell: ./bin/bundle install
  args:
    chdir: "{{ diaspora_dir }}"
  environment:
    RAILS_ENV: production
  register: bundle_install
  when: bundler is succeeded and bundle_config is succeeded
  tags:
    - gem
    - bundler
    - update
    - database
    - assets
    - diaspora

# Pick a table of Diaspora's schema db and check against it.
# If the database is populated, the 'tags' table should exist.
# If it exists, the output should be: (1 row).
- name: Check if database is already populated
  become_user: postgres
  shell: psql -d diaspora_production -c "SELECT relname FROM pg_class WHERE relname='tags';" | grep '(1 row)'
  ignore_errors: true
  changed_when: false
  register: check_db
  tags:
    - database
    - seed

- name: Initial Seed of database (destructive, runs only the first time)
  become_user: diaspora
  shell: ./bin/bundle exec "rake db:create db:schema:load"
  args:
    chdir: "{{ diaspora_dir }}"
  environment:
    RAILS_ENV: production
  when: check_db.stdout == "(0 rows)"
  tags:
    - database
    - seed

- name: Migrate database
  become_user: diaspora
  shell: ./bin/bundle exec "rake db:migrate"
  args:
    chdir: "{{ diaspora_dir }}"
  environment:
    RAILS_ENV: production
  when: bundle_install is succeeded
  tags:
    - update
    - database
    - migration
    - diaspora

# Recompile assets
- name: Recompile assets
  become_user: diaspora
  shell: ./bin/bundle exec "rake tmp:cache:clear" && ./bin/bundle exec "rake assets:clean" && ./bin/bundle exec "rake assets:precompile"
  args:
    chdir: "{{ diaspora_dir }}"
  environment:
    RAILS_ENV: production
  when: bundle_install is succeeded
  notify:
    - restart unicorn
  tags:
    - update
    - assets
    - diaspora
