---
# Diaspora systemd services
- name: Copy diaspora.target
  sudo: yes
  copy:
    src: diaspora.target
    dest: "{{ systemd_path }}/diaspora.target"
    owner: root
    group: root
    mode: 644
  notify:
    - daemon reload
    - restart diaspora
  tags:
    - diaspora
    - config
    - systemd

- name: Copy sidekiq systemd service
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - src: diaspora-sidekiq.service.j2
      dest: "{{ systemd_path }}/diaspora-sidekiq.service"
  notify:
    - daemon reload
    - restart sidekiq
  tags:
    - diaspora
    - config
    - systemd
    - sidekiq

- name: Copy unicorn systemd service
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
    - src: diaspora-unicorn.service.j2
      dest: "{{ systemd_path }}/diaspora-unicorn.service"
  notify:
    - daemon reload
    - restart unicorn
  tags:
    - diaspora
    - config
    - systemd
    - unicorn

- name: Enable systemd watchdog
  lineinfile: >
    dest=/etc/systemd/system.conf
    regexp="RuntimeWatchdogSec"
    line="RuntimeWatchdogSec\=20s"
    state=present
  notify:
    - daemon reload
  tags:
    - config
    - systemd
