---
# Diaspora systemd services
- name: Copy unicorn systemd service
  template:
    src: unicorn.service.j2
    dest: "{{ systemd_path }}/unicorn.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload
    - restart unicorn
  tags:
    - diaspora
    - config
    - systemd
    - unicorn

- name: Copy sidekiq systemd service
  template:
    src: sidekiq.service.j2
    dest: "{{ systemd_path }}/sidekiq.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload
    - restart sidekiq
  tags:
    - diaspora
    - config
    - systemd
    - sidekiq

- name: Create unicorn pid directory
  file:
    path: /run/diaspora/
    state: directory
    owner: diaspora
    group: diaspora
    mode: 0755
  tags:
    - unicorn

- name: Copy diaspora tmpfiles to persist directories
  template:
    src: diaspora.tmpfiles.d
    dest: /etc/tmpfiles.d/diaspora.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - unicorn

- name: Enable systemd watchdog
  lineinfile: >
    dest=/etc/systemd/system.conf
    regexp="RuntimeWatchdogSec"
    line="RuntimeWatchdogSec\=20s"
    state=present
  notify:
    - daemon reload
  tags:
    - config
    - systemd

- name: Enable unicorn/sidekiq services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - unicorn
    - sidekiq
