---
- name: Make sure needed directories exist
  file: path={{ item }} state=directory recurse=yes
  with_items:
    - /root/bin
    - "{{ backup_path }}/latest"
  register: bin_path

- name: Create diaspora backup dir
  file:
    path: "{{ backup_path }}"
    state: directory
    recurse: yes
    owner: diaspora
    group: diaspora
    mode: 0755

- name: Copy backup script
  template:
    src: backup.sh.j2
    dest: /root/bin/backup.sh
    owner: root
    group: root
    mode: 0700
  when: bin_path|success

- name: Add a cronjob symlink
  file:
    path: /etc/cron.weekly/backup.sh
    src: /root/bin/backup.sh
    state: link
    force: yes

- name: Download backup.log
  fetch: >
    src={{ item.src }}
    dest={{ item.dest }}
    flat=yes
    fail_on_missing=yes
    validate_checksum=no
  with_items:
    - src: "{{ backup_path }}/backup.log"
      dest: "{{ downloads_path }}"
  tags:
    - logs
