---
# tasks file for common

- name: Install EPEL repo
  yum: name=epel-release state=latest
  tags:
    - yum
    - pkg
    - epel

- name: Install system dependencies
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tar
    - make
    - gcc
    - gcc-c++
    - automake
    - net-tools
    - libcurl-devel
    - libxml2-devel
    - libffi-devel
    - libxslt-devel
  tags:
    - yum
    - pkg
