---
# handlers file for diaspora
- name: restart diaspora
  service: name=gitlab.target state=restarted

- name: restart unicorn
  service: name=diaspora-unicorn state=restarted

- name: restart sidekiq
  service: name=diaspora-sidekiq state=restarted

- name: daemon reload
  command: systemctl daemon-reload
