---
# handlers file for diaspora
- name: restart unicorn
  service: name=unicorn state=restarted

- name: restart sidekiq
  service: name=sidekiq state=restarted

- name: daemon reload
  command: systemctl daemon-reload
