---
# handlers file for diaspora
- name: restart diaspora
  command: systemctl restart diaspora.target

- name: restart unicorn
  command: systemctl restart diaspora-unicorn.service

- name: restart sidekiq
  command: systemctl restart diaspora-sidekiq.service

- name: daemon reload
  command: systemctl daemon-reload
