---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2

- name: Init db
  shell: postgresql-setup initdb creates=/var/lib/pgsql/data/pg_ident.conf

- name: Start and enable database
  service: name=postgresql state=started enabled=yes

- name: Create Diaspora User
  become_user: postgres
  postgresql_user:
    name: diaspora
    password: "{{ pg_diaspora_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER

    #- name: Create Prosody User
    #  become_user: postgres
    #  postgresql_user:
    #    name: prosody
    #    password: "{{ pg_prosody_password }}"
    #    db: diaspora_production
    #    priv: CONNECT/users:SELECT

- name: Create Diaspora Database.
  become_user: postgres
  postgresql_db:
    name: diaspora_production
    owner: diaspora

- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql

- name: Copy .pgpass
  template:
    src: pgpass.j2
    dest: /home/diaspora/.pgpass
    owner: diaspora
    group: diaspora
    mode: 0600
