---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2

- name: Init db
  shell: postgresql-setup initdb creates=/var/lib/pgsql/data/pg_ident.conf

- name: Start and enable database
  service: name=postgresql state=started enabled=yes

- name: Create Database User
  become_user: postgres
  postgresql_user:
    user: "{{ database.user }}"
    password: "{{ database.password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER

- name: Create Database.
  become_user: postgres
  postgresql_db:
    name: "{{ database.name }}"
    owner: "{{ database.user }}"

- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql
