---
- hosts: librenet.gr
  sudo: yes
  gather_facts: true
  vars:
    backup_path: "/var/backup"
    downloads_path: "../downloads/{{ ansible_hostname }}/"

  tasks:
    - name: Make sure needed directories exist
      file: path={{ item }} state=directory recurse=yes
      with_items:
        - /root/bin
        - /var/backup/latest
      register: bin_path

    - name: Copy backup script
      copy: >
        src=../scripts/backup.sh
        dest=/root/bin/backup.sh
        owner=root
        group=root
        mode=700
      when: bin_path|success

    - name: Run backup script
      shell: >
        chdir=/root/bin/
        bash backup.sh

    - name: Download backup.log
      fetch: >
        src={{ item.src }}
        dest={{ item.dest }}
        flat=yes
        fail_on_missing=yes
        validate_checksum=no
      with_items:
        - src: "{{ backup_path }}/backup.log"
          dest: "{{ downloads_path }}"
      tags:
        - logs
