---

- hosts: all
  sudo: yes
  gather_facts: false
  tasks:

    - name: Restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx
        - diaspora

    - name: Restart unicorn
      service: name=unicorn state=restarted
      tags:
        - unicorn
        - diaspora

    - name: Restart sidekiq
      service: name=sidekiq state=restarted
      tags:
        - sidekiq
        - diaspora

    - name: Restart redis
      service: name=redis state=restarted
      tags:
        - redis
        - diaspora

    - name: Restart mariadb
      service: name=mariadb state=restarted
      tags:
        - mariadb
        - mysql

    - name: Restart ssh
      service: name=ssh state=restarted
      tags:
        - ssh
