---
- hosts: all
  sudo: yes
  gather_facts: false
  tasks:

    - name: Enable nginx
      service: name=nginx state=started enabled=yes
      tags:
        - nginx
        - diaspora

    - name: Enable unicorn
      service: name=unicorn state=started enabled=yes
      tags:
        - unicorn
        - diaspora

    - name: Enable sidekiq
      service: name=sidekiq state=started enabled=yes
      tags:
        - sidekiq
        - diaspora

    - name: Enable redis
      service: name=redis state=started enabled=yes
      tags:
        - redis
        - diaspora

    - name: Enable postgres
      service: name=postgres state=started enabled=yes
      tags:
        - postgres
        - database

    - name: Enable sshd
      service: name=sshd state=started enabled=yes
      tags:
        - ssh

    - name: Enable ntp
      service: name=ntpd state=started enabled=yes
      tags:
        - ntp
