---

- hosts: librenet.gr
  become: true
  gather_facts: false
  tasks:

    - name: Restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx
        - diaspora

    - name: Restart unicorn
      service: name=unicorn state=restarted
      tags:
        - unicorn
        - diaspora

    - name: Restart sidekiq
      service: name=sidekiq state=restarted
      tags:
        - sidekiq
        - diaspora

    - name: Restart redis
      service: name=redis state=restarted
      tags:
        - redis
        - diaspora

    - name: Restart postgres
      service: name=postgresql state=restarted
      tags:
        - postgres
        - mysql

    - name: Restart ssh
      service: name=ssh state=restarted
      tags:
        - ssh

    - name: Restart prosody
      service: name=prosody state=restarted
      tags:
        - prosody

    - name: Restart camo
      service: name=camo state=restarted
      tags:
        - camo
