---
- hosts: all
  gather_facts: false
  tasks:

    - name: status nginx
      command: systemctl status nginx.service
      register: nginx_status
      failed_when:  nginx_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - nginx
        - diaspora

    - name: status unicorn
      command: systemctl status unicorn.service
      register: unicorn_status
      failed_when:  unicorn_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - unicorn
        - diaspora

    - name: status sidekiq
      command: systemctl status sidekiq.service
      register: sidekiq_status
      failed_when:  sidekiq_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - sidekiq
        - diaspora

    - name: status redis
      command: systemctl status redis.service
      register: redis_status
      failed_when:  redis_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - redis
        - diaspora

    - name: status postgres
      command: systemctl status postgresql.service
      register: postgres_status
      failed_when:  postgres_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - postgres
        - mysql

    - name: status prosody
      command: systemctl status prosody.service
      register: prosody_status
      failed_when:  prosody_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - prosody

    - name: status camo
      command: systemctl status camo.service
      register: camo_status
      failed_when:  camo_status.rc != 0
      changed_when: false
      ignore_errors: true
      tags:
        - camo
